# Generated by Django 3.1.2 on 2022-12-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221204_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='scope',
            new_name='tag',
        ),
    ]
