# Generated by Django 3.1.2 on 2022-12-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='changing_temp',
            new_name='temperature',
        ),
    ]
